// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD-BRY_V366E_7UX7qSqay2dktMUE7AFFA',
    appId: '1:993178814299:web:88928618f26e0b6e0a7c7e',
    messagingSenderId: '993178814299',
    projectId: 'todo-challenge-f1586',
    authDomain: 'todo-challenge-f1586.firebaseapp.com',
    storageBucket: 'todo-challenge-f1586.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC0b49vby-92z_xknr5gINtya2-lT6WVEc',
    appId: '1:993178814299:android:54f4e01dfba84c360a7c7e',
    messagingSenderId: '993178814299',
    projectId: 'todo-challenge-f1586',
    storageBucket: 'todo-challenge-f1586.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC7aBX_SyL_Ydq3GckeH4qZBowsp94dwrQ',
    appId: '1:993178814299:ios:93f73345cc740f530a7c7e',
    messagingSenderId: '993178814299',
    projectId: 'todo-challenge-f1586',
    storageBucket: 'todo-challenge-f1586.appspot.com',
    iosClientId:
        '993178814299-buutei1sjemnl7hu149t9jpqsnlo6t9u.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterChallenge',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC7aBX_SyL_Ydq3GckeH4qZBowsp94dwrQ',
    appId: '1:993178814299:ios:93f73345cc740f530a7c7e',
    messagingSenderId: '993178814299',
    projectId: 'todo-challenge-f1586',
    storageBucket: 'todo-challenge-f1586.appspot.com',
    iosClientId:
        '993178814299-buutei1sjemnl7hu149t9jpqsnlo6t9u.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterChallenge',
  );
}
